# fly.toml app configuration file generated for consulta-handicap on 2023-04-24T10:18:28-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "consulta-handicap"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gru"

[build]

[env]

[mounts]
  destination = "/data"
  encrypted = false
  processes = []
  source = "handicap_data"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250